sudo: required

notifications:
  email: false

os:
  - linux

language: ruby
rvm:
  - 2.5.1

services:
  - docker

install:
  - pip install --user cwltool==1.0.20180820141117

script:
  - cd test/conformance-53 && make
